ingressRoute:
  dashboard:
    enabled: false
additionalArguments:
  - "--api.insecure=true"
  - "--providers.file.watch=true"
  - "--providers.file.directory=/traefik/configuration"
  - "--log.level=ERROR"
  - "--log.format=json"
  - "--accessLog"
  - "--accessLog.format=json"
service:
  enabled: true
  externalIPs:
    - 192.168.125.158
    - 192.168.125.159
  persistence:

extraObjects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: traefik-api
    spec:
      type: ClusterIP
      selector:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: traefik-default
      ports:
        - port: 8080
          name: traefik
          targetPort: 9000
          protocol: TCP

  - apiVersion: v1
    kind: Secret
    metadata:
      name: traefik-dashboard-auth-secret
    type: kubernetes.io/basic-auth
    stringData:
      username: admin
      password: CITA@2024

  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: traefik-dashboard-auth
    spec:
      basicAuth:
        secret: traefik-dashboard-auth-secret

  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: traefik-dashboard
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: default-traefik-dashboard-auth@kubernetescrd
    spec:
      rules:
        - host: l158.utc.edu.vn
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: traefik-api
                    port:
                      name: traefik
                      
deployment:
  additionalVolumes:
    - name: traefik-folders
      hostPath:
        path: /home/traefik
additionalVolumeMounts:
  - name: traefik-folders
    mountPath: /traefik