apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-web-ui
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`l158.utc.edu.vn`)
    kind: Rule
    services:
    - name: traefik
      port: dashboard