---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  selector:
    app: traefik
  ports:
    - protocol: TCP
      name: dashboard
      port: 80
---      
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-web-ui
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`l158.utc.edu.vn`)
    kind: Rule
    services:
    - name: traefik-dashboard
      port: web