---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: traefik
spec:
  selector:
    app: traefik
  ports:
  - name: web
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: IngressRoute
metadata:
  name: traefik-web-ui
  namespace: traefik
spec:
  rules:
  - host: l158.utc.edu.vn
    http:
      paths:
      - path: /
        backend:
          service:
            name: traefik-web-ui
            port: web
