---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: traefik
spec:
  selector:
    app: traefik
  ports:
  - name: web
    port: 80
    targetPort: 8080
---
apiVersion: apiextensions.k8s.io/v1
kind: IngressRoute
metadata:
  name: traefik-web-ui
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`l158.utc.edu.vn`)
    kind: Rule
    services:
    - name: traefik-web-ui
      port: web
